
services:
  service1:
    build:
      context: ./router  # Directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./router:/app

  service2:
    build:
      context: ./python-exe  # Directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./python-exe:/app
    
  service3:
    build:
      context: ./java-exe #Directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./java-exe:/app

  service4:
    build:
      context: ./dart-exe #Directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./dart-exe:/app



